import numpy as np
import logging
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
from typing import List, Tuple, Any

logger = logging.getLogger(__name__)

class AnomalyDetector:
    """
    Module responsible for detecting anomalous subgraphs using a One-Class SVM.
    It trains on a 'normal baseline' of dense embeddings generated by the GNN encoder
    and isolates subgraphs that fall outside the normality hypersphere.
    """

    def __init__(self, nu: float = 0.05, kernel: str = 'rbf', gamma: str = 'scale'):
        """
        Initializes the One-Class SVM anomaly detector.

        Args:
            nu: An upper bound on the fraction of training errors and a lower bound of the fraction of support vectors.
                In this context, it represents the expected percentage of anomalies in the training set (e.g., 5%).
            kernel: Specifies the kernel type to be used in the algorithm.
            gamma: Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.
        """
        self.model = OneClassSVM(nu=nu, kernel=kernel, gamma=gamma)
        self.scaler = StandardScaler()
        self.is_trained = False

    def train(self, embeddings: np.ndarray):
        """
        Trains the One-Class SVM model on the provided baseline embeddings.

        Args:
            embeddings: Numpy array of shape (n_samples, n_features) representing normal behavior.
        """
        if len(embeddings) == 0:
            logger.warning("No embeddings provided for training. Model not trained.")
            return

        logger.info(f"Training Anomaly Detector on {len(embeddings)} baseline subgraphs...")

        # Scale the embeddings to ensure features contribute equally to the distance computation
        scaled_embeddings = self.scaler.fit_transform(embeddings)

        # Fit the One-Class SVM to learn the hypersphere enclosing the normal baseline
        self.model.fit(scaled_embeddings)
        self.is_trained = True
        logger.info("Anomaly Detector training completed.")

    def detect(self, embeddings: np.ndarray, graph_ids: List[str]) -> Tuple[List[str], np.ndarray]:
        """
        Calculates the distance of new vectors and isolates subgraphs that fall
        outside the normal hypersphere.

        Args:
            embeddings: Numpy array of shape (n_samples, n_features) representing new behavior.
            graph_ids: List of graph identifiers corresponding to the embeddings.

        Returns:
            A tuple containing:
                - List of anomalous graph IDs.
                - Numpy array of anomaly scores (decision function values). Lower means more anomalous.
        """
        if not self.is_trained:
            raise ValueError("The Anomaly Detector has not been trained yet. Call train() first.")

        if len(embeddings) == 0:
            logger.info("No embeddings provided for detection.")
            return [], np.array([])

        logger.info(f"Detecting anomalies in {len(embeddings)} subgraphs...")

        # Scale the new embeddings using the scaler fitted during training
        scaled_embeddings = self.scaler.transform(embeddings)

        # Predict anomaly labels: +1 (normal), -1 (anomaly)
        predictions = self.model.predict(scaled_embeddings)

        # Get decision function scores: distance to the separating hyperplane.
        # Negative values correspond to anomalies.
        scores = self.model.decision_function(scaled_embeddings)

        anomalous_ids = []
        for i, pred in enumerate(predictions):
            if pred == -1: # Anomaly detected
                anomalous_ids.append(graph_ids[i])
                logger.debug(f"Anomaly detected in graph '{graph_ids[i]}' with score {scores[i]:.4f}")

        logger.info(f"Anomaly detection finished. Found {len(anomalous_ids)} anomalous subgraphs.")
        return anomalous_ids, scores
